# Generated by Django 3.0.5 on 2020-05-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='unnamed.jpg', upload_to='images/'),
        ),
    ]
